FROM ubuntu:18.04

ARG DEBIAN_FRONTEND=noninteractive
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ARG AWS_REGION=eu-central-1

RUN apt update
RUN apt install awscli tomcat9 -y
RUN aws s3 cp s3://mybucket.test.com/hello.war /usr/local/tomcat/webapps/hello.war
EXPOSE 8080
CMD [ "\usr\local\tomcat\bin\catlina.sh", "run"]


