FROM ubuntu:18.04

ARG DEBIAN_FRONTEND=noninteractive
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ARG AWS_REGION=eu-central-1

RUN apt update
RUN apt install awscli maven default-jdk git -y
WORKDIR home/ubuntu/
RUN git clone https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
WORKDIR home/ubuntu/boxfuse-sample-java-war-hello/
RUN mvn package
RUN aws s3 cp /home/ubuntu/boxfuse-sample-java-war-hello/target/hello-1.0.war s3://mybucket.test.com/hello.war
